# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71a28482a4e6ba894c08636d41909e1555372293c20ba91102780ed4feb0694a8c85cbd85a1ec894587137e08b9c302e6b3af568c3bc1d324381558cdba3e6af

test:
  secret_key_base: 8942bfcb67a3692fb72ff12ffe1b26379afb07b1ae6107705632bb125b34df03d527e2c1f1403b304b3a095c3170da3e10d36528603fe720b30a421cf3ca05df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
